sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
env:
  matrix:
  - DB=mysql
  - DB=sqlite
  - DB=postgresql
  global:
    secure: dmT9iNPQJ8HgjUWMar3snqmuH7D3xdsJmKLkAXuCKVsKdHDBq+rlITguDyoHREsXN8K+fQrnCBoPv1P4SQ9SRnBeIcMKgx+OTc1uNJJgVtVDOFrwc7VEgHyV4R7MOK7fFhT5boDZEHsZbX0qsKfu68+60z53Opooq9Mj5q/AukgWzN5maphzFAbYqye60k5QKBDIVaUYnpsCfNfoCop1fmLDMOt4Lodcq6e6jNRa1DLeyn6m0JBOjT711inTbIH2+dyHM7gSdusOKtFg4MX09Oi98Gfa1lZFHZsT8vpGZ6TohgKLl2mx0u7kKidBiuPCzRVbk59ZU5YcwB7gO9OMMw3rkc04TTj9GXxGPfZz7Rv1E+U6NK4S4ywezJnjfRQuvOQp5aSt8MV7piLzaZWUHG7eKqoOjE3X+6BIYG3YQ42+tP2+5/92rLsK+B/U+sF5d2XBkIqnG5fBE/AkI89kCPAl8wbfFxPm6G/t59ID5gprEKTXCNhQ3hZX+iB/GODDnlB5iF+N3av5LExTm3e1tDloV5oUYVNXLrs45F58hb4I0K+sCj60UoH90IncfdjphvLvTpVpxmaVO22E/a66Ei+6SbbTdK+7eBEBCdudWRtxtH3whop6P1+6QjzrIL7rU/elJJPaWyneC6gWnF3e2g0G2UWVWZdgwAKhut8fFwY=
gemfile:
- gemfiles/Gemfile.rails-5.0-stable
- gemfiles/Gemfile.rails-5.1-stable
- gemfiles/Gemfile.rails-5.2-stable
- gemfiles/Gemfile.rails-6.0-stable
- Gemfile
services:
- postgresql
- mysql
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- export RAILS_ENV=test
- bundle exec rake app:db:create app:db:migrate
- bundle exec rspec spec
after_script:
- "./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json coverage/.resultset.json"
- if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
